{% set name = "Flask-Moment" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ff4cc0c4f8ec6798e19ba17fac409a8090f21677da6b21e3e1e4450344d8ed71

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - flask

  run:
    - python >=3.6
    - flask

test:
  imports:
    - flask_moment
  commands:
    - pip check
  requires: 
    - pip

about:
  home: http://github.com/miguelgrinberg/flask-moment/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Formatting of dates and times in Flask templates using moment.js.'
  dev_url: http://github.com/miguelgrinberg/flask-moment/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
