{% set name = "Flask-Moment" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "8379acdc9cda1227573ae52aac2e5b4b391e77ed300c70d49b0a929d0aa76680" %}
{% set build = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python >=3.6
    - setuptools
    - flask

  run:
    - python >=3.6
    - flask

test:
  imports:
    - flask_moment

about:
  home: http://github.com/miguelgrinberg/flask-moment/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Formatting of dates and times in Flask templates using moment.js.'
  dev_url: http://github.com/miguelgrinberg/flask-moment/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
