{% set name = "Flask-Moment" %}
{% set version = "1.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 33307ecd4af8290b6df6a9828ff55ac0977d0567817f9bc0f69803d22ed2b55c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - flask
  run:
    - python >=3.6
    - flask
    - packaging

test:
  imports:
    - flask_moment
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/miguelgrinberg/flask-moment/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Formatting of dates and times in Flask templates using moment.js.
  dev_url: http://github.com/miguelgrinberg/flask-moment/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
