{% set name = "Flask-Moment" %}
{% set version = "0.5.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "20d86b88a156eeda040530b329dbf996e731576ead295ea079a62fc0915b21d8" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  noarch: python
  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt


requirements:
  build:
    - python
    - setuptools
    - flask

  run:
    - python
    - flask

test:
  imports:
    - flask_moment

about:
  home: http://github.com/miguelgrinberg/flask-moment/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Formatting of dates and times in Flask templates using moment.js.'
  dev_url: http://github.com/miguelgrinberg/flask-moment/

extra:
  recipe-maintainers:
    - pmlandwehr
