{% set name = "Flask-Moment" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 2f8969907cbacde4a88319792e8f920ba5c9dd9d99ced2346cad563795302b88

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv


requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - flask
  run:
    - python >={{ python_min }}
    - flask
    - packaging

test:
  imports:
    - flask_moment
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/miguelgrinberg/flask-moment/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Formatting of dates and times in Flask templates using moment.js.
  dev_url: http://github.com/miguelgrinberg/flask-moment/

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
