travis:
  secure:
    BINSTAR_TOKEN: liVh14nKOp9BIyeuX+1Fkb9lMShaPLxVGL/BHGRcjggxn5LBveLUzisyUsIeBnmVSOkT11JCjBmLwE613fiWSBlLy2BQoVoh7Z4eIhqXAzg0u8zcyLiqk+4xhZ0d2U3TgaE3zr0fgwELVGFvCT9wv5H3HTlhH8SbR1Imw0+Twnbu6NBDYujFzCqa2y3b42GkuYUC9Zq0ad6ob9zSJt64KJsCCMMKoUQhvXCRqPZG9KaJwfRzO0LLEwQ5j2IKlnGWkzFnYf4/vXzu1ZYYuGkUzwHF/84MFRspGrQSaOfyCCxGWgHuTkRRu30AV9TZ1EtVRaPU/hylXeTMgyu6p2zpkBlyEwl2gOw1vxAmFpR2ZUgfU+G2ikLDpXvarBFN8OINm+owjEJeBt0TQecFJFAhboyr0dqgBNp8WDU/qOHHYJ4Qt6sAJ7fKfYeEBrDSpmr8TxeEQB6sbR/uokFnS7qisoJJ5u66mygd06LFOZPLrjsRU41bfTh5E30i0gMJ3OZAqA0DNdZ4QmqMPRyph211puw3iIHQT5/gV5DP8aqsEhDp5xleC9oSvXN90fJFdVnyRluUASzyQMzbFlyWF6TRv5OObMFFWz2cJBsWn0jsGl/cvN3mbZcTmNniACzpdPRq+wyVps7L8u3uJOcYjY0mZmXDYYf5aQcpQDV1049VJ/M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
