travis:
  secure:
    BINSTAR_TOKEN: Me2+Nw+lDtSB0gdNWqneiujHY+/PwxP1pxAQWGUfGjanW3545IE+qOOnj7XYvIkhSzhpDhxxL3flv28yQGRZ+xEueUmJi2eMJALmixNNPStfAn2NVvaJA/jZS6yiXzD1v5nDou62FVB/76kPBgStILJnhamOoZ0niLkPPs2AAH8s8YrXuxSuMR7o3GjDLnIqdvRXWoXB2azUTM0Jhw9piz4cCsgPsnaLh2HvYtDzXGaJX5SVFP2owHapD0LDSP7KaQSTdJPGy+GNeITUpUn/GYdknys09cyWx+FcPhaA868e8R587Q1yxbhPjpfeKqIHy1MTEMlzKkZEwTlbCj+pn6JlNfd2JtKzYwUDUc273vnevGNjGyqky36wEsuRS+y9DvT55ssya6tKH4TJCzRt/VdfEsDf3ah/cNlk6+aqxf8JlJT6YxUhDxUnnfaWk9+OCOaR0aoO/w33y1E+wCKIvTsc5F5C67a04AEZuOtfe0SvaojjidLH6txuflJIdMFMBMWNs1+21kDFMTmZvlMBoY1REaIFUqo50na0DDOKrBWQTYxXYBBHUBsFrDjDs+rRYog8a7cn10L3piMLCm6E47vFSFbJGQ2sTMJlO0IY4SxlQlOS456SYTgOxacwznmeMT93EEwxXvFTLmYUvIYFdTLVK2bFEMo6duMdcBjEqac=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
